#!/bin/bash
### BEGIN INIT INFO
# Provides:          doorbot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
case "$1" in
start)
forever start /opt/doorBot/forever.json
;;
stop)
forever stop /opt/doorBot/index.js
;;
*)
echo "Usage: $0 {start|stop|restart}"
esac